<a href="https://colab.research.google.com/github/rrankawat/pytorch-basic/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


*   A torch.Tensor is a multi-dimentional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
*   Default data type of float32.
*   More suitable for deep learning than a numpy array.



# LISTS (Python)

In [28]:
# 1-D
list_1d = [1, 2, 3, 4, 5, 6]
list_1d

[1, 2, 3, 4, 5, 6]

In [29]:
# 2-D
list_2d = [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 10]]
list_2d

[[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS (ML)

In [30]:
import numpy as np

In [31]:
# 2-D
np_2d = np.random.rand(3, 4)
np_2d

array([[0.66143269, 0.50461396, 0.48830635, 0.2003703 ],
       [0.32834872, 0.6199419 , 0.9057087 , 0.76437586],
       [0.44736913, 0.38590282, 0.85052919, 0.19137568]])

In [32]:
np_2d.dtype

dtype('float64')

In [33]:
# 3-D
np_3d = np.random.rand(2, 3, 4)
np_3d

array([[[0.26294248, 0.26375447, 0.83267661, 0.0076114 ],
        [0.75387694, 0.37354608, 0.75812627, 0.72214734],
        [0.3641399 , 0.23348631, 0.54003925, 0.34139506]],

       [[0.23717291, 0.39352042, 0.14542749, 0.65327382],
        [0.62725319, 0.86131398, 0.82109834, 0.41464206],
        [0.79961321, 0.61413263, 0.94546395, 0.71263231]]])

# TENSORS (DL)

In [34]:
import torch

In [35]:
# 2-D
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.2919, -0.3179, -0.2087, -1.7516],
        [-0.1240, -0.3334, -0.4896, -0.1760],
        [-0.9974,  2.8572, -0.9536,  0.6295]])

In [36]:
tensor_2d.dtype

torch.float32

In [37]:
# 3-D
tensor_3d = torch.randn(2, 3, 4)
tensor_3d

tensor([[[-0.7158, -0.5613, -0.8523, -0.0380],
         [ 0.3141,  0.7126,  0.7653,  0.5977],
         [-0.2935, -1.0326,  0.1314,  1.0202]],

        [[ 0.0488,  1.6134, -0.4695,  0.9255],
         [-1.0223,  0.0396, -0.2967,  0.3614],
         [ 0.9014, -0.2493,  1.5141, -1.1748]]])

# Numpy To Tensor

In [38]:
my_tensor = torch.tensor(np_2d)
my_tensor

tensor([[0.6614, 0.5046, 0.4883, 0.2004],
        [0.3283, 0.6199, 0.9057, 0.7644],
        [0.4474, 0.3859, 0.8505, 0.1914]], dtype=torch.float64)