<a href="https://colab.research.google.com/github/rrankawat/pytorch-basic/blob/main/02_Tensors_With_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
*   default data type of float32.
*   More suitable for deep learning than a numpy array.


In [5]:
import torch
import numpy as np

# LISTS

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3, 4)
np1

array([[0.62767803, 0.53166001, 0.97220112, 0.65534037],
       [0.59161042, 0.71014347, 0.20927592, 0.53480894],
       [0.31580583, 0.20868579, 0.19366484, 0.67069876]])

In [13]:
np1.dtype

dtype('float64')

# TENSORS

In [14]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.8618, -0.5814,  0.1362,  1.1207],
        [ 1.1553,  0.7814,  0.2373,  2.0419],
        [ 0.4142,  1.0454, -1.0794,  0.3077]])

In [15]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6277, 0.5317, 0.9722, 0.6553],
        [0.5916, 0.7101, 0.2093, 0.5348],
        [0.3158, 0.2087, 0.1937, 0.6707]], dtype=torch.float64)