<a href="https://colab.research.google.com/github/rrankawat/pytorch-basic/blob/main/02_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import torch

# Reshape

In [24]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Reshape: Manually
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# Reshape with -1: Automatic
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

# View

In [28]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Differences

In [30]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
my_torch7 = my_torch5.view(2,5)
my_torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
my_torch5[1] = 41
my_torch5

tensor([ 0, 41,  2,  3,  4,  5,  6,  7,  8,  9])

In [34]:
my_torch6

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [35]:
my_torch7

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

# Slices

In [36]:
my_torch8 = torch.arange(10)
my_torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Grab a specific item
my_torch8[7]

tensor(7)

In [39]:
# Grab a slice
my_torch9 = my_torch8.reshape(5,2)
my_torch9

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [40]:
my_torch9[:, 1] # up until

tensor([1, 3, 5, 7, 9])

In [41]:
# Return a column
my_torch9[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])