<a href="https://colab.research.google.com/github/rrankawat/pytorch-basic/blob/main/03_Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR MATH OPERATIONS


* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and uh, Longhand
* Reassignment



In [19]:
import torch
import numpy as np

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

### Addition

In [21]:
# Directly
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
# Sub Function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

### Subtraction

In [23]:
# Directly
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [24]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

### Multiplication

In [25]:
# Directly
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [26]:
# Sub Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

### Division

In [27]:
# Directly
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [28]:
# Sub Function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

### Reminder Modulus

In [29]:
# Directly
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [30]:
# Sub Function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

### Exponents (Power)

In [31]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])