<a href="https://colab.research.google.com/github/rrankawat/pytorch-basic/blob/main/04_Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR MATH OPERATIONS


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [3]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [5]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# Addition Longhand
torch.add(tensor_a, tensor_b)


tensor([ 6,  8, 10, 12])

In [7]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
# Sub Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# Multiplicaiton
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [18]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
# Reassignment '_'
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [21]:
tensor_a

tensor([1, 2, 3, 4])

In [22]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([ 6,  8, 10, 12])